au = importdata('../../Desktop/BSEconomy/DataFiles/AfterUtility.txt');
bu = importdata('../../Desktop/BSEconomy/DataFiles/BeforeUtility.txt');
histogram(au,100);
hold on;
histogram(bu,50);
title('Before and After Utility Distribution of 50 Simulations (50 Players, 50 Rounds)');
xlabel('Total Utility');
ylabel('Number of Players');
legend('After','Before');
savefig('../../Desktop/BSEconomy/PlotFiles/Utility.fig');
print('../../Desktop/BSEconomy/Graphs/Utility.png','-dpng');
close();

ta = importdata('../../Desktop/BSEconomy/DataFiles/TotalAmount.txt');
histogram(ta,100);
title('Total Amount Distribution of 50 Simulations (50 Players, 50 Rounds)');
xlabel('Total Amount');
ylabel('Number of Players');
savefig('../../Desktop/BSEconomy/PlotFiles/Amount.fig');
print('../../Desktop/BSEconomy/Graphs/Amount.png','-dpng');
close();